### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by knowuh**
@pjanik  In my work with Firebase I included many commits that were related to just general cleanup. I pulled those changes into this PR. Here is what you should see:

- eslint rules.
- enforce single quotes as the norm.
- removal of legacy `bower` artifacts
- stop git tracking of build artifacts

One question I had about the above:  Do we expect the `dist/` directory to exist on the master branch as part of any other tool build?  I was trying to avoid reading diffs with too much noise because of `dist/`.

### CODE REVIEW

**Comment by pjanik** [comment]
Looks great to me 👍 I'm just not sure about bower and dist, though. 

> Do we expect the dist/ directory to exist on the master branch as part of any other tool build?

I don't use this pattern anymore in new JS projects that use webpack and are deployed to NPM (since we can define has prepublish script that builds the lib). In this case, I was using `dist` as this lib is still deployed to bower. Bower just uses git tags AFAIR, so prebuilt version of the lib probably has to be checked into the repository. And I haven't removed bower when I was switching this project to webpack, as LARA still pulls this lib from rails-assets which is based on bower.

I'm definitely happy to remove it, but we'd need to find an alternative way of deployment and update LARA. Probably a typical copy-paste approach could be justified to simplify this lib and LARA. rails-assets and bower don't seem to be very popular anymore.

**Comment by knowuh** [comment]
Thanks for reviewing.  

LARA is using rails-assets.org for shutterbug and modulejs too. I had forgotten about how this worked.

We should simplify if possible but my enthusiasm for removing `dist/` might be premature.  We still want to distribute libraries maybe using tagged github releases?

Two simple approaches for this come to mind:

1. We could ignore (in our minds) the changes that happen in under `dist/` while we are reviewing code.  This would be a little noisy while reviewing commits.

2. Create an additional build step that copies files to `dist/` (whereas the default webpack output path would be something else ... TBD)

You have thought about this much more than I have.  I would love to get your thoughts if you have time.

**Comment by pjanik** [comment]
> We could ignore (in our minds) the changes that happen in under dist/ while we are reviewing code. This would be a little noisy while reviewing commits.

Personally, I just skip changes under /dist. It's a bit annoying, but I wouldn't say it's a big problem to me.

> Create an additional build step that copies files to dist/ (whereas the default webpack output path would be something else ... TBD)

Not sure if I understand. We'd still have /dist folder, right? It's just that we don't need to remember to build project before committing changes (or tagging)? It would be helpful for sure. I guess you can add git pre-commit handler, but I guess it needs to be setup manually by every developer.

In general I feel that the biggest problem is how to distribute JS libraries to our rails apps. As I said, since rails-assets doesn't seem like a solution that we'll use in the future, I'd be fine with removing it completely and copy-pasting prebuilt libraries into LARA. We do it anyway with quite a lot of JS libs in LARA and Portal. 

I've done some research how to integrate NPM / webpack with old Rails app and I haven't found anything that looked stable and convincing enough. But I did probably 1-2 years ago, things might have changed. Especially now when Rails 5.1 has just added support to NPM.

**Comment by knowuh** [comment]
We haven't talked about this in a while.  I agree with your points, and I am still not quite sure what to do.  😆  

It may be safest to put the the `./dist` folder and `bower.json` back in on the principle of 'do no harm'.  We don't really have a better alternative right now other than copy/paste.

**Pull request merged**
