### PR TITLE
chore: Use 's3-deploy-action' (PT-185267555)

### PR DESCRIPTION
**Pull request by 433eros**

### CODE REVIEW

**Review by pjanik — COMMENTED** [review]
Looks good, but aren't we missing webpack.config update (DEPLOY_PATH)?

**Review by pjanik — CHANGES_REQUESTED** [review]
> I forgot to copy drawing-tool.css so I made it recursively copy everything now (including examples/ which works fine like this). It seems like we were never doing the symlink trick before so I think this is fine for now.

I think it doesn't matter whether we used that before or not. We must use HTMLWebpackPlugin + DEPLOY_PATH for the release action to work. 

The reason for DEPLOY_PATH is to set it in index-top.html, so it works when copied to the top level. This cannot be done automatically, as index-top should NOT work when placed in its default location `/version/v1.2.3/index-top.html`, but it should work only when copied to the top level `/`. Webpack cannot guess that it's our intention, so that's why we need DEPLOY_PATH and WebpackHTMLPlugin. 

It means that we cannot simply use CopyPlugin like here, but we need to change the processing of index.html file to HTMLWebpackPlugin like in other repositories.

Probably @scytacki could confirm if I'm right here. I guess it'd be important to fully understand it, as then we might break release actions in other repos (or already did).

Having said all that... This project is an example of another tricky repo for the new deploy action. We have multiple index files in the example dir... :wink: So, theoretically, we should build all these examples HTML files using HTMLWebpackPlugin with -top.html suffix, and then copy them to top-level using custom release.yml action.

My suggestion would be to skip release.yml at all in this repository. It's a library that we release via NPM. And I think it's fine if examples are accessed via `/version/v1.2.3` or `/branch/master` links. I'd just update README so the URLs there are not broken.

**Comment by lublagg** [comment]
Hi @pjanik, I just removed the release.yml file and re-requested your review. There were no URL's in the README files to update.

**Review by pjanik — APPROVED** [review]
@lublagg, it looks good, but there's a demo link. The first line under the readme header. 

After we merge this PR, it should be:
https://models-resources.concord.org/drawing-tool/branch/master/examples/index.html
as the old one (https://models-resources.concord.org/drawing-tool/examples/index.html) will never be updated again.

I'm accepting this PR anyway assuming you can push this change and merge the PR. Thanks!

**Pull request merged**
