### PR TITLE
Firebase storage example

### PR DESCRIPTION
**Pull request by knowuh**
This is a prototype drawing-tool extension which allows collaborators to work together on a drawing.

Extension points were created within the drawing tool to support services interested in saving & loading events.

There are some known limitations with this firebase implementation:

1. The example uses one firebase instance.  
2. The firebase API is being abused. Instead of storing a monolithic blob, we should be handling specific events on data nodes with finer granularity.

Future work should address the two points above.

### CODE REVIEW

**Comment by knowuh** [comment]
Hi @pjanik -- I have rebased this on changes to the minor-cleanup branch. (in which I restored the `bower.json` and `./dist/` paths).

I also added a few commits -- the only major one being 579453e which allows for serialized data to be loaded from a plain object (in addition to a JSON string).

Saving and Loading from a plain object is much better for cases where we store drawing data in firebase. Firebase will only have to distribute a smaller change to listening clients.

**Comment by pjanik** [comment]
I've looked at the code, it's not a small PR, but in general it looks good. 👍 

> The firebase API is being abused. Instead of storing a monolithic blob, we should be handling specific events on data nodes with finer granularity.

Although this approach is way simpler and cleaner, so IMHO as long as it's fast enough and it's working as expected, it feels okay to me.

My main concern is that adding Firebase storage seems to be more app-specific rather than lib-specific. It's quite opinionated, I guess it includes CC account details and so on. So, I'd rather provide generic extension points in DrawingTool like `.notifySave` and other things you added, but I'd try to keep firebase external (maybe one page in /examples dir could implement it?). Not sure if it's a lot of work and if it's worth it right now, so I'm fine with merging this PR if it makes sense now, but I'd try to do it at least in the future.

**Comment by knowuh** [comment]
@pjanik  You are right, it really doesn't make sense. I have removed all the firebase code from this repo, and have started putting together a new hosted app project for the collaboration piece called [codraw](https://github.com/concord-consortium/codraw).

Please look at commit ddc0023 that removes the collaborative (MSU) related changes.

**Comment by pjanik** [comment]
Nice! Looks good. 👍

**Pull request merged**
